# -*- coding: utf-8 -*-
"""간암 예측 로직

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UVqkEaGWZJpOCIvYUqthZoBmC_DNEir
"""

import json
import joblib
import pandas as pd
from openai import OpenAI

# 모델 로드
try:
    MODEL_PATH = "liver_cancer_xgb_model.pkl"
    model = joblib.load(MODEL_PATH)
except:
    MODEL_PATH = "model1/liver_cancer_xgb_model.pkl"
    try:
        model = joblib.load(MODEL_PATH)
    except:
        model = None

# 1. 모델 입력 전체 Feature 리스트 (snake_case)
LIVER_FEATURES = [
    "age", "gender", "bmi", "alcohol_consumption", "smoking_status",
    "hepatitis_b", "hepatitis_c", "cirrhosis_history",
    "family_history_cancer", "physical_activity_level", "diabetes"
]

# 2. 필수 입력 변수 (이것만 질문함)
REQUIRED_LIVER_KEYS = [
    "age", "gender", "bmi", "alcohol_consumption", "smoking_status",
    "family_history_cancer", "physical_activity_level", "diabetes"
]

# 3. 선택 입력 변수
# hepatitis_b, hepatitis_c, cirrhosis_history -> 언급 없으면 0(없음) 처리

def convert_general_to_liver_data(general_data):
    """
    [STEP 2 추가] 일반 암 진단 데이터를 간암 모델용(snake_case)으로 변환
    """
    liver_data = {}

    # 1. Key Mapping (Camel -> snake) & Type Casting

    if general_data.get("Age") is not None:
        liver_data["age"] = general_data["Age"]

    if general_data.get("Gender") is not None:
        liver_data["gender"] = general_data["Gender"] # 0:M, 1:F (일치 가정)

    if general_data.get("BMI") is not None:
        liver_data["bmi"] = general_data["BMI"]

    if general_data.get("PhysicalActivity") is not None:
        liver_data["physical_activity_level"] = general_data["PhysicalActivity"]

    # 2. Binary Feature Mapping (존재하면 1, 아니면 0)

    # Smoking (0/1 -> 0/1)
    if general_data.get("Smoking") is not None:
        liver_data["smoking_status"] = general_data["Smoking"]

    # Alcohol (0~5 -> 0/1)
    if general_data.get("Alcohol") is not None:
        # 일반에서 0(안마심)이면 0, 1 이상(마심)이면 1
        liver_data["alcohol_consumption"] = 1 if general_data["Alcohol"] > 0 else 0

    # Family History (Integer -> 0/1)
    if general_data.get("Family_History") is not None:
        liver_data["family_history_cancer"] = 1 if general_data["Family_History"] > 0 else 0

    # Diabetes는 일반 데이터에 없으므로 매핑 불가 (질문 대상)

    return liver_data

def gpt_extraction(history, user_input, client):
    """
    간암 진단을 위한 특화된 정보 추출 함수
    """
    system_prompt = """
    너는 '간암(Liver Cancer) 발병 확률 예측 모델'을 위한 데이터 추출기야.
    사용자의 입력에서 정보를 추출해서 아래 포맷의 JSON(snake_case key)으로 반환해.

    [필수 항목]
    1. age (정수)
    2. gender (0:Male, 1:Female) - 남녀 구분
    3. bmi (실수)
    4. alcohol_consumption (0/1 또는 수치) - 음주 여부
    5. smoking_status (0/1 또는 수치) - 흡연 여부
    6. family_history_cancer (0/1) - 암 가족력
    7. physical_activity_level (0~10) - 운동량
    8. diabetes (0/1) - 당뇨병 유무

    [선택 항목] - 사용자가 언급하면 추출, 아니면 null (굳이 묻지 않음)
    - hepatitis_b (0/1) - B형 간염
    - hepatitis_c (0/1) - C형 간염
    - cirrhosis_history (0/1) - 간경변증 이력

    [규칙]
    - 명확히 언급되지 않은 값은 null로 둔다.
    - 예/아니오 질문은 1/0으로 변환.
    - JSON 형식 {"age": 45, "hepatitis_b": 0, ...} 형태로 출력.
    """

    messages = [{"role": "system", "content": system_prompt}]
    messages.extend(history[-5:])
    messages.append({"role": "user", "content": user_input})

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=messages,
            response_format={"type": "json_object"}
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        print(f"GPT Extraction Error: {e}")
        return None

def generate_ask_question(collected_data, missing_keys):
    """
    간암 전용 추가 질문 생성 (필수 항목만)
    """
    name_map = {
        "age": "나이",
        "gender": "성별",
        "bmi": "키와 몸무게 (BMI 계산을 위해 필요합니다)",
        "alcohol_consumption": "음주를 하시나요?",
        "smoking_status": "흡연을 하시나요?",
        "family_history_cancer": "가족 중 암 환자가 있으신가요?",
        "physical_activity_level": "평소 운동량은 어느 정도인가요? (0~10)",
        "diabetes": "당뇨병 진단을 받은 적이 있으신가요?"
    }

    # 필수 항목 중 수집되지 않은 것만 필터링
    real_missing = [
        key for key in missing_keys
        if key in REQUIRED_LIVER_KEYS and collected_data.get(key) is None
    ]

    questions = []
    count = 0
    for key in real_missing:
        if key in name_map:
            questions.append(f"- {name_map[key]}")
            count += 1
            if count >= 3:
                break

    if not questions:
        return "간암 진단을 위한 필수 정보가 모두 확인되었습니다."

    return "간암 정밀 진단을 위해 다음 정보가 필요합니다.\n\n" + "\n".join(questions)

def predict_liver_cancer(data_dict):
    """
    간암 예측 실행
    """
    if model is None:
        return -1, "모델 로드 실패"

    try:
        input_df = pd.DataFrame([data_dict])

        # 결측치 처리 (필수/선택 모두)
        for col in LIVER_FEATURES:
            if col not in input_df.columns or pd.isna(input_df[col].iloc[0]):
                # 간염, 간경변 등 병력 정보(선택항목)는 '없음(0)'으로 가정
                input_df[col] = 0

        # 컬럼 순서 정렬
        input_df = input_df[LIVER_FEATURES]

        prob = model.predict_proba(input_df)[0][1]
        return prob
    except Exception as e:
        print(f"Prediction Error: {e}")
        return 0.0