# -*- coding: utf-8 -*-
"""최종 통합 앱

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9BH9fe81FFFTTJoWZcaRe5GwvAHX39R
"""

import streamlit as st
from openai import OpenAI
import pandas as pd
import os
from dotenv import load_dotenv

# --- 로직 모듈 임포트 ---
import project1_logic as logic_gen
import project1_logic_lug as logic_lung
import project1_logic_liver as logic_liver

load_dotenv()
try:
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
except:
    client = None

st.set_page_config(page_title="AI 다중 암 진단 서비스", layout="wide")

# --- 1. 세션 상태 초기화 ---
def init_session_state():
    if 'diagnosis_mode' not in st.session_state:
        st.session_state.diagnosis_mode = "GENERAL" # GENERAL, LUNG, LIVER
    if 'messages' not in st.session_state:
        st.session_state.messages = []
    if 'collected_data' not in st.session_state:
        st.session_state.collected_data = {k: None for k in ["Age", "Gender", "BMI", "Smoking", "Alcohol", "Family_History", "PhysicalActivity"]}
    if 'lung_data' not in st.session_state:
        st.session_state.lung_data = {}
    if 'liver_data' not in st.session_state:
        st.session_state.liver_data = {}
    if 'step' not in st.session_state:
        st.session_state.step = "COLLECTING" # COLLECTING, PREDICTED

init_session_state()

# --- 2. 사이드바 (컨트롤 및 디버깅) ---
with st.sidebar:
    # [기능 1] 초기화 버튼 (테스트 편의성)
    if st.button("🔄 진단 다시 시작하기", use_container_width=True):
        for key in list(st.session_state.keys()):
            del st.session_state[key]
        init_session_state()
        st.rerun()

    st.divider()

    # 모드별 제목 및 체크리스트
    mode_titles = {
        "GENERAL": "🩺 일반 암 위험도",
        "LUNG": "🫁 폐암 정밀 진단",
        "LIVER": "🥃 간암 정밀 진단"
    }
    st.header(mode_titles.get(st.session_state.diagnosis_mode, "진단 서비스"))

    st.subheader("📋 입력 정보 현황")
    checklist_area = st.empty()

    def render_checklist():
        mode = st.session_state.diagnosis_mode
        if mode == "GENERAL":
            target = st.session_state.collected_data
            keys = list(target.keys())
            name_map = {"Age": "나이", "Gender": "성별", "BMI": "BMI", "Smoking": "흡연", "Alcohol": "음주", "Family_History": "가족력", "PhysicalActivity": "운동"}
        elif mode == "LUNG":
            target = st.session_state.lung_data
            keys = logic_lung.REQUIRED_LUNG_KEYS
            name_map = {k: k for k in keys}
            name_map.update({"Age": "나이", "Gender": "성별", "Alcohol use": "음주", "Smoking": "흡연", "Passive Smoker": "간접흡연"})
        elif mode == "LIVER":
            target = st.session_state.liver_data
            keys = logic_liver.REQUIRED_LIVER_KEYS
            name_map = {k: k for k in keys}
            name_map.update({"age": "나이", "gender": "성별", "bmi": "BMI", "alcohol_consumption": "음주", "smoking_status": "흡연", "diabetes": "당뇨"})
        else:
            return

        text = ""
        for k in keys:
            val = target.get(k)
            icon = "✅" if val is not None else "⬜"
            label = name_map.get(k, k)
            text += f"{icon} **{label}**\n\n"
        checklist_area.markdown(text)

    render_checklist()

    # [기능 2] 시스템 상태 모니터링 (디버깅용)
    st.divider()
    with st.expander("🛠️ 시스템 상태 (Debug)"):
        st.markdown("**모델 로드 상태:**")

        def status_icon(model_obj):
            return "🟢 로드됨" if model_obj is not None else "🔴 실패"

        st.write(f"- 일반 암 모델: {status_icon(logic_gen.model)}")
        st.write(f"- 폐암 모델: {status_icon(logic_lung.model)}")
        st.write(f"- 간암 모델: {status_icon(logic_liver.model)}")

        st.markdown("---")
        st.markdown("**세션 데이터:**")
        st.json(st.session_state.get('collected_data', {}))
        st.write(f"Current Mode: **{st.session_state.diagnosis_mode}**")

# --- 3. 메인 화면 ---
st.title("🤖 AI 헬스케어 어시스턴트")

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# --- [BRIDGE] 모드 전환 버튼 ---
if st.session_state.diagnosis_mode == "GENERAL" and st.session_state.step == "PREDICTED":
    st.divider()
    st.markdown("##### 💡 더 정밀한 진단을 원하시나요?")
    c1, c2 = st.columns(2)

    # 폐암 전환
    if c1.button("🫁 폐암 정밀 진단 시작", use_container_width=True):
        st.session_state.diagnosis_mode = "LUNG"
        st.session_state.step = "COLLECTING"
        # 데이터 매핑
        st.session_state.lung_data = logic_lung.convert_general_to_lung_data(st.session_state.collected_data)

        # 안내 메시지 트리거
        missing = [k for k in logic_lung.REQUIRED_LUNG_KEYS if st.session_state.lung_data.get(k) is None]
        if missing:
            q = logic_lung.generate_ask_question(st.session_state.lung_data, missing)
            msg = "기존 정보를 바탕으로 **폐암 정밀 진단** 모드로 전환합니다.\n\n" + q
        else:
            msg = "폐암 진단에 필요한 모든 정보가 준비되었습니다. 바로 분석해드릴까요?"
        st.session_state.messages.append({"role": "assistant", "content": msg})
        st.rerun()

    # 간암 전환
    if c2.button("🥃 간암 정밀 진단 시작", use_container_width=True):
        st.session_state.diagnosis_mode = "LIVER"
        st.session_state.step = "COLLECTING"
        st.session_state.liver_data = logic_liver.convert_general_to_liver_data(st.session_state.collected_data)

        missing = [k for k in logic_liver.REQUIRED_LIVER_KEYS if st.session_state.liver_data.get(k) is None]
        if missing:
            q = logic_liver.generate_ask_question(st.session_state.liver_data, missing)
            msg = "기존 정보를 바탕으로 **간암 정밀 진단** 모드로 전환합니다.\n\n" + q
        else:
            msg = "간암 진단에 필요한 모든 정보가 준비되었습니다."
        st.session_state.messages.append({"role": "assistant", "content": msg})
        st.rerun()

# --- 4. 대화 로직 ---
if prompt := st.chat_input("답변을 입력해주세요..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    current_mode = st.session_state.diagnosis_mode
    response_text = ""

    # [A] GENERAL
    if current_mode == "GENERAL":
        extracted = logic_gen.gpt_extraction(st.session_state.messages, prompt, client)
        if extracted:
            for k, v in extracted.items():
                if v is not None: st.session_state.collected_data[k] = v
            render_checklist()

        missing = [k for k, v in st.session_state.collected_data.items() if v is None]
        if missing:
            response_text = logic_gen.generate_ask_question(st.session_state.collected_data, missing)
        else:
            # 예측
            data = st.session_state.collected_data
            input_df = pd.DataFrame([{
                'Age': data['Age'], 'Gender': data['Gender'], 'BMI': data['BMI'],
                'Smoking': data['Smoking'], 'Alcohol': data['Alcohol'],
                'Family_History': 1 if data['Family_History'] > 0 else 0,
                'PhysicalActivity': data['PhysicalActivity']
            }])
            if logic_gen.model:
                prob = logic_gen.model.predict_proba(input_df)[0][1]
                response_text = logic_gen.interpret_result_with_gpt(prob, client)
            else:
                response_text = "⚠️ 모델을 불러오지 못해 예측할 수 없습니다."

            st.session_state.step = "PREDICTED"
            st.session_state.messages.append({"role": "assistant", "content": response_text})
            st.rerun()

    # [B] LUNG
    elif current_mode == "LUNG":
        extracted = logic_lung.gpt_extraction(st.session_state.messages, prompt, client)
        if extracted:
            for k, v in extracted.items():
                if v is not None: st.session_state.lung_data[k] = v
            render_checklist()

        missing = [k for k in logic_lung.REQUIRED_LUNG_KEYS if st.session_state.lung_data.get(k) is None]
        if missing:
            response_text = logic_lung.generate_ask_question(st.session_state.lung_data, missing)
        else:
            prob = logic_lung.predict_lung_cancer(st.session_state.lung_data)
            response_text = f"🫁 **폐암 정밀 분석 결과**\n\n예측된 위험도는 **{prob*100:.1f}%** 입니다."
            st.session_state.step = "PREDICTED"

    # [C] LIVER
    elif current_mode == "LIVER":
        extracted = logic_liver.gpt_extraction(st.session_state.messages, prompt, client)
        if extracted:
            for k, v in extracted.items():
                if v is not None: st.session_state.liver_data[k] = v
            render_checklist()

        missing = [k for k in logic_liver.REQUIRED_LIVER_KEYS if st.session_state.liver_data.get(k) is None]
        if missing:
            response_text = logic_liver.generate_ask_question(st.session_state.liver_data, missing)
        else:
            prob = logic_liver.predict_liver_cancer(st.session_state.liver_data)
            response_text = f"🥃 **간암 정밀 분석 결과**\n\n예측된 위험도는 **{prob*100:.1f}%** 입니다."
            st.session_state.step = "PREDICTED"

    st.session_state.messages.append({"role": "assistant", "content": response_text})
    with st.chat_message("assistant"):
        st.markdown(response_text)