# -*- coding: utf-8 -*-
"""폐암 예측 로직

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RBFkv5BGUZES0GrGShezMWuxOVWxuEUK
"""

import json
import joblib
import pandas as pd
from openai import OpenAI

# 모델 로드
try:
    MODEL_PATH = "lung_xgb_model.pkl"
    model = joblib.load(MODEL_PATH)
except:
    MODEL_PATH = "model1/lung_xgb_model.pkl"
    try:
        model = joblib.load(MODEL_PATH)
    except:
        model = None

# 1. 모델 입력 전체 Feature 순서 (변경 불가)
LUNG_FEATURES = [
    "Age", "Gender", "Air Pollution", "Alcohol use", "Dust Allergy",
    "OccuPational Hazards", "Genetic Risk", "chronic Lung Disease",
    "Balanced Diet", "Obesity", "Smoking", "Passive Smoker",
    "Chest Pain", "Weight Loss", "shortness of Breath", "Dry Cough"
]

# 2. 필수 입력 변수 (이것만 질문함)
REQUIRED_LUNG_KEYS = [
    "Age", "Gender", "Alcohol use", "Dust Allergy", "Genetic Risk",
    "chronic Lung Disease", "Balanced Diet", "Obesity", "Smoking",
    "Passive Smoker", "Dry Cough"
]

# 3. 선택 입력 변수 (누락 시 기본값 처리)
# Air Pollution, OccuPational Hazards, Chest Pain, Weight Loss, shortness of Breath

def convert_general_to_lung_data(general_data):
    """
    [STEP 2 추가] 일반 암 진단 데이터(collected_data)를 폐암 모델용으로 변환
    """
    lung_data = {}

    # 1. Age (Copy)
    if general_data.get("Age") is not None:
        lung_data["Age"] = general_data["Age"]

    # 2. Gender 변환
    # 일반 모델: 0(남), 1(여)
    # 폐암 모델: 1(남), 2(여) (프롬프트 기준)
    if general_data.get("Gender") is not None:
        lung_data["Gender"] = 1 if general_data["Gender"] == 0 else 2

    # 3. Smoking (0/1 -> 1/None)
    # 일반 진단에서 '비흡연(0)'이면 폐암 수치 1(최저)로 자동 설정
    # '흡연(1)'이면 정확한 정도(1~8)를 모르므로 None으로 두어 질문 유도
    if general_data.get("Smoking") == 0:
        lung_data["Smoking"] = 1

    # 4. Alcohol (0~5 -> 1/None)
    # '비음주(0)'이면 폐암 수치 1(최저)로 설정
    if general_data.get("Alcohol") == 0:
        lung_data["Alcohol use"] = 1

    # 그 외 Genetic Risk, Obesity 등은 척도가 다르므로
    # 일반 데이터(Family_History, BMI)를 바로 쓰지 않고 정밀 질문을 하도록 둠

    return lung_data

def gpt_extraction(history, user_input, client):
    """
    폐암 진단을 위한 특화된 정보 추출 함수
    """
    system_prompt = """
    너는 '폐암(Lung Cancer) 발병 확률 예측 모델'을 위한 데이터 추출기야.
    사용자의 입력과 대화 내역에서 정보를 추출해서 아래 포맷의 JSON으로 반환해.

    [필수 항목] - 없으면 null 반환
    1. Age (정수)
    2. Gender (1:남성, 2:여성) - 입력이 텍스트면 변환
    3. Alcohol use (1~8)
    4. Dust Allergy (1~8)
    5. Genetic Risk (1~7)
    6. chronic Lung Disease (1~7)
    7. Balanced Diet (1~7)
    8. Obesity (1~7)
    9. Smoking (1~8)
    10. Passive Smoker (1~8)
    11. Dry Cough (1~9)

    [선택 항목] - 사용자가 언급하면 추출, 아니면 null (굳이 묻지 않음)
    - Air Pollution (1~8)
    - OccuPational Hazards (1~8)
    - Chest Pain (1~9)
    - Weight Loss (1~8)
    - shortness of Breath (1~9)

    [규칙]
    - 수치형 데이터(1~8 등)는 사용자의 표현(조금, 보통, 심함 등)을 보고 적절히 정수로 변환. (예: '전혀 없다'=1, '매우 심하다'=8/9)
    - JSON 형식 {"Age": 50, "Air Pollution": 3, ...} 만 출력하라.
    """

    messages = [{"role": "system", "content": system_prompt}]
    messages.extend(history[-5:])
    messages.append({"role": "user", "content": user_input})

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=messages,
            response_format={"type": "json_object"}
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        print(f"GPT Extraction Error: {e}")
        return None

def generate_ask_question(collected_data, missing_keys):
    """
    폐암 전용 추가 질문 생성 (필수 항목만 질문)
    """
    name_map = {
        "Alcohol use": "술은 얼마나 자주, 많이 드시나요? (1-8)",
        "Dust Allergy": "평소 먼지 알레르기가 있으신가요? (1-8)",
        "Genetic Risk": "가족 중 폐암 이력이 있으신가요? (1-7)",
        "chronic Lung Disease": "만성 폐질환을 앓은 적이 있으신가요? (1-7)",
        "Balanced Diet": "식사는 규칙적이고 균형 잡히게 하시나요? (1-7)",
        "Obesity": "본인의 비만도는 어느 정도라고 생각하시나요? (1-7)",
        "Smoking": "직접 흡연을 하시나요? 하신다면 어느 정도인가요? (1-8)",
        "Passive Smoker": "간접 흡연에 노출되는 빈도는 어떤가요? (1-8)",
        "Dry Cough": "마른 기침이 자주 나오나요? (1-9)",
        "Age": "나이를 알려주세요.",
        "Gender": "성별을 알려주세요."
    }

    # missing_keys 중 '필수 항목'이면서 '아직 수집되지 않은(None)' 것만 필터링
    real_missing = [
        key for key in missing_keys
        if key in REQUIRED_LUNG_KEYS and collected_data.get(key) is None
    ]

    questions = []
    count = 0
    for key in real_missing:
        if key in name_map:
            questions.append(f"- {name_map[key]}")
            count += 1
            if count >= 3:
                break

    if not questions:
        return "진단을 위한 필수 정보가 모두 수집되었습니다. 분석을 시작할까요?"

    return "폐암 정밀 진단을 위해 다음 필수 정보들이 더 필요합니다.\n\n" + "\n".join(questions)

def predict_lung_cancer(data_dict):
    """
    수집된 데이터를 DataFrame으로 변환 후 예측
    """
    if model is None:
        return -1, "모델을 불러오지 못했습니다."

    try:
        input_df = pd.DataFrame([data_dict])

        # 1. 필수/선택 모든 컬럼에 대해 결측치 처리
        for col in LUNG_FEATURES:
            # 값이 없으면 기본값 1 (Low/None)로 채움
            if col not in input_df.columns or pd.isna(input_df[col].iloc[0]):
                input_df[col] = 1

        # 2. 컬럼 순서 강제 정렬 (모델 학습 시점과 동일하게)
        input_df = input_df[LUNG_FEATURES]

        # 3. 예측
        prob = model.predict_proba(input_df)[0][1] # Class 1(발병) 확률
        return prob
    except Exception as e:
        print(f"Prediction Error: {e}")
        return 0.0